Parameters:
    ec2PublicIP:
        Type: String

Resources:
    DNS:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: Z1001812ZAY4J3FHO8MW
            Name: jjenano.pruebas.cloud
            ResourceRecords: [!Ref ec2PublicIP]
            TTL: '900'      
            Type: A